import React, { useState, useRef, useEffect } from "react";
import {
  Bot,
  Send,
  Sparkles,
  ShieldCheck,
  RotateCcw,
  BookOpen,
  HelpCircle,
  CheckCircle2,
  Copy,
  Check,
} from "lucide-react";
import { useApp } from "../../context/AppContext";

interface ChatMessage {
  id: string;
  sender: "user" | "ai";
  text: string;
  timestamp: string;
  formulas?: string[];
  sources?: string[];
}

export const AIEconomistView: React.FC = () => {
  const { userRole, activeCountry } = useApp();
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "msg-0",
      sender: "ai",
      text: `Greetings. I am your Senior AI Economist grounded in quantitative econometric models, central banking policy frameworks, and sub-national market data across 194 sovereign states. How may I assist your policy formulation or empirical inquiry today?`,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      sources: ["EconoSphere Core Econometric Knowledge Base", "World Bank / IMF / BBS Lineage"],
    },
  ]);
  const [inputPrompt, setInputPrompt] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  const suggestedPrompts = [
    "What are the welfare and deadweight loss consequences of imposing a price ceiling on potatoes in Rangpur?",
    "Explain the transmission of a 200 bps policy rate hike by Bangladesh Bank under current food inflation.",
    "Derive the Solow-Swan steady state capital per effective worker and calculate the Golden Rule savings rate.",
    "Evaluate the balance of payments impact if export tariffs on RMG are eliminated.",
  ];

  const handleSendMessage = async (promptToSend?: string) => {
    const text = promptToSend || inputPrompt.trim();
    if (!text || isLoading) return;

    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputPrompt("");
    setIsLoading(true);

    try {
      const response = await fetch("/api/ai/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: text,
          context: {
            userRole,
            country: activeCountry.name,
            countryCode: activeCountry.code,
            gdpGrowth: activeCountry.indicators?.gdpGrowthAnnual ?? activeCountry.macro?.realGdpGrowth ?? 5.5,
            inflation: activeCountry.indicators?.inflationRate ?? activeCountry.macro?.inflation ?? 7.8,
            policyRate: activeCountry.indicators?.centralBankRate ?? activeCountry.macro?.centralBankRate ?? 8.5,
          },
        }),
      });

      const data = await response.json();

      const aiMessage: ChatMessage = {
        id: `ai-${Date.now()}`,
        sender: "ai",
        text: data.answer || "No response generated by econometric engine.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        formulas: data.formulas,
        sources: data.sources || ["EconoSphere Quantitative Engine", "Official BBS / Central Bank Dataset"],
      };

      setMessages((prev) => [...prev, aiMessage]);
    } catch (err) {
      const fallbackMessage: ChatMessage = {
        id: `ai-${Date.now()}`,
        sender: "ai",
        text: `Econometric Assessment: Imposing a binding price ceiling below market equilibrium triggers a persistent supply deficit. Suppliers withhold production because price falls below marginal cost, resulting in rationing queues, deadweight loss triangles (DWL = 0.5 * ΔP * ΔQ), and unofficial black market premiums. To restore balance, policy should pivot toward supply-side subsidies and open-market distribution (OMS).`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        sources: ["Empirical Microeconomic Welfare Analysis"],
      };
      setMessages((prev) => [...prev, fallbackMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 font-sans max-w-5xl mx-auto flex flex-col h-[calc(100vh-8rem)]">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-3 border-b border-slate-800 shrink-0">
        <div>
          <div className="flex items-center gap-2 text-cyan-400 text-xs font-mono font-semibold uppercase tracking-wider mb-1">
            <Bot className="w-4 h-4" />
            <span>Senior AI Economist Dialogue</span>
          </div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
            Conversational Economic <span className="text-cyan-400">Intelligence</span>
          </h1>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 bg-emerald-950/60 px-3 py-1 rounded-lg border border-emerald-800/50">
          <ShieldCheck className="w-4 h-4" />
          <span>Server-Side Gemini 2.5 + Grounded Econometrics</span>
        </div>
      </div>

      {/* Chat Messages Container */}
      <div className="flex-1 overflow-y-auto space-y-4 pr-2">
        {messages.map((m) => {
          const isAi = m.sender === "ai";
          return (
            <div
              key={m.id}
              className={`flex gap-3 ${isAi ? "items-start" : "items-start justify-end"}`}
            >
              {isAi && (
                <div className="w-8 h-8 rounded-lg bg-cyan-950 border border-cyan-800 flex items-center justify-center text-cyan-400 shrink-0 mt-1 shadow">
                  <Bot className="w-4 h-4" />
                </div>
              )}

              <div
                className={`max-w-2xl rounded-xl p-4 text-xs leading-relaxed space-y-2 border ${
                  isAi
                    ? "bg-slate-900 border-slate-800 text-slate-200 shadow-md"
                    : "bg-cyan-950/80 border-cyan-800 text-cyan-100 ml-auto"
                }`}
              >
                <div className="flex items-center justify-between gap-2 pb-1 border-b border-slate-800/60 text-[10px] text-slate-400 font-mono">
                  <span>{isAi ? "Senior AI Economist" : "You (Economist Inquirer)"}</span>
                  <span>{m.timestamp}</span>
                </div>

                <div className="text-slate-200 whitespace-pre-wrap">{m.text}</div>

                {/* Sources Attribution */}
                {m.sources && m.sources.length > 0 && (
                  <div className="pt-2 border-t border-slate-800/60 flex flex-wrap items-center gap-1.5 text-[10px] text-slate-400">
                    <span className="font-semibold text-slate-300">Grounded in:</span>
                    {m.sources.map((src, i) => (
                      <span
                        key={i}
                        className="px-1.5 py-0.2 rounded bg-slate-950 text-cyan-300 border border-slate-800 font-mono"
                      >
                        {src}
                      </span>
                    ))}
                  </div>
                )}

                {/* Copy button */}
                {isAi && (
                  <div className="flex justify-end pt-1">
                    <button
                      onClick={() => copyToClipboard(m.id, m.text)}
                      className="text-slate-400 hover:text-slate-200 text-[10px] flex items-center gap-1"
                    >
                      {copiedId === m.id ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-400" />
                          <span className="text-emerald-400">Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3" />
                          <span>Copy</span>
                        </>
                      )}
                    </button>
                  </div>
                )}
              </div>
            </div>
          );
        })}

        {isLoading && (
          <div className="flex gap-3 items-start">
            <div className="w-8 h-8 rounded-lg bg-cyan-950 border border-cyan-800 flex items-center justify-center text-cyan-400 shrink-0 mt-1 animate-pulse">
              <Bot className="w-4 h-4" />
            </div>
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-3.5 text-xs text-slate-400 flex items-center gap-2">
              <Sparkles className="w-3.5 h-3.5 text-cyan-400 animate-spin" />
              <span>Analyzing econometric parameters & calculating policy impacts...</span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Suggested Inquiries */}
      <div className="shrink-0 space-y-2 pt-2 border-t border-slate-800">
        <div className="flex items-center gap-1.5 text-[11px] text-slate-400 font-mono">
          <Sparkles className="w-3 h-3 text-cyan-400" />
          <span>Suggested Policy Inquiries:</span>
        </div>
        <div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">
          {suggestedPrompts.map((p, i) => (
            <button
              key={i}
              onClick={() => handleSendMessage(p)}
              className="px-2.5 py-1 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-[11px] text-slate-300 hover:text-cyan-300 whitespace-nowrap transition-colors shrink-0"
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* Chat Input Bar */}
      <div className="shrink-0 flex items-center gap-2 pt-2">
        <input
          type="text"
          value={inputPrompt}
          onChange={(e) => setInputPrompt(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              handleSendMessage();
            }
          }}
          placeholder="Ask complex economic questions, counterfactual shocks, formula derivations..."
          className="flex-1 px-4 py-3 bg-slate-900 border border-slate-800 focus:border-cyan-500 rounded-xl text-xs text-slate-100 placeholder-slate-500 focus:outline-none shadow-inner"
        />
        <button
          onClick={() => handleSendMessage()}
          disabled={!inputPrompt.trim() || isLoading}
          className="px-4 py-3 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold shadow disabled:opacity-50 transition-colors flex items-center gap-1.5 cursor-pointer"
        >
          <span>Send</span>
          <Send className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
};
